### ISSUE TITLE
Conflict between OLED Display and SPS30

### ISSUE THREAD

**Issue by DCBene** [opendata-stuttgart/sensors-software#735] opened 2020-06-10 14:15 UTC
Hey there fellows,

So, I've just built my second AirRohr, this time using a DHT22 and a SPS30 for data gathering on a NodeMCU V3.3 ESP8266. One thing that has startled me is the SPS30's fan running constantly. Is that supposed to be the case? My first AirRohr still uses an SDS011 which only seems to power up its fan when measuring. But that is just an observation. 

The actual bug I've come across is my inability to use the SPS30 with an OLED 1306 connected at the same time. When the display is connected and activated in the configuration settings, the debug window tells me the SPS30 isn't connected ('not found') and tells me to check my wiring. 

When the display is connected but not activated in the configuration, everything works fine.

I have the display's and the SPS30's SCL port connected to D4 and the SDA ports connect to D3.

When activated, the display works just fine.

This issue applies both to the BETA and latest stable software versions.

Unfortunately, I'm in no way a programmer. So, reporting this issue is the only thing I can contribute at the moment. Sorry for that.

Looking forward to hear your suggestions - cheers!

**Comment by DeeKey** [comment] 2020-07-20 12:58
Have you checked connections?
SPS30 (I2C, 5V)
Pinout: 1 2 3 4 5
    Pin 1 (5V) -> Pin VU/VIN
    Pin 2 (SDA) -> Pin D3 (GPIO0)
    Pin 3 (SCL) -> Pin D4 (GPIO2)
    Pin 4 (SEL) -> Pin GND
    Pin 5 (GND) -> Pin GND

OLED displays with SSD1306 (I2C, 128x64 pixels)
    VCC -> Pin VU
    GND -> Pin GND
    SCL -> Pin D4 (GPIO2)
    SDA -> Pin D3 (GPIO0)

**Comment by DeeKey** [comment] 2020-07-20 13:19
Did you use 10kOm resistors? There is a schematic in this case:
https://github.com/opendata-stuttgart/sensors-software/issues/738

**Comment by DeeKey** [comment] 2020-07-20 15:04
Also try to use the latest Beta version.

**Comment by hbitter** [comment] 2020-07-21 15:56
Hi DCBene,

1. SPS30 fan is running constantly "by design" of the firmware, SPS30 it is not switched on and off. The SPS30 takes more than 30 seconds, that the values have settled. So it makes no sense to switch it on and off. The lifetime of the sensor is more than 8 years nonstop operation, that is what sensirons says and hopefully it is true. Sensirion recommended also continously opertion.

2. SPS30 is working only with beta version of the NodeMCU firmware (NRZ-2020-130-B6) based on problems with I²C communication in the NRZ-2020-129 firmware version.

3. On the I²C Bus my recommendation would be to use 4,7K pullups for SCL and SDA but it doesn' t matter in this case.

4. Using an OLED SSD1306 display with the beta version NRZ-2020-130-B6 can be a bit problematic as I found today. For my adafruit OLED SSD1306 display I had to change the I²C address from 0x3c to 0x3d. More problematic was, that the firmware always crashed, when I changed the configuration to OLED SSD1306 or SH1106. I had to do the confiration with NRZ-2020-129 and than flash my compiled version of NRZ-2020-130-B6.

5. I tried to add the SPS30 to that configuration with the result that the SPS30 was not found at startup. So no values from the SPS30 but display running. Taking the OLED display out of the configuration but leaving it still connected, changed it in a way, that the SPS30 was now found and values are shown on the local website.

6. I also checked it with an OLED SH1106 display with the same result, no simultaneous working of SPS30 and OLED display only one or the other.

I will have time to look in more detail into it from mid of August on not earlier.
Regards,
Helmut

**Comment by hbitter** [comment] 2020-08-05 16:03
It is a problem with the SSD1306 lib. The SSD1306 lib (as well as SSH11106 lib) sets the I²C Clock to about 500kHz during initialisation. This is to high for the SPS30, the SPS30 is specified for I²C standard speed of 100kHz and not more.

Workaround:
Set I²C speed back to 100kHz after display initialisation. The following picture shows it for NRZ-2020-130-B6.

![Image 3](https://user-images.githubusercontent.com/559304/89434467-dd12d100-d743-11ea-9545-c21a5ffe0ce4.jpg)

If you are not familiar with compiling the airrohr firmware, I can sent you the airrohr-firmware.ino.bin. Send me a PM: helmut.bitter (at) t-online.de

Here is a screenshot from the start of the NodeMCU now finding display and SPS30:

![Image 4](https://user-images.githubusercontent.com/559304/89435890-c7061000-d745-11ea-89a7-b57805b8a71a.jpg)

Regards,
Helmut

**Comment by dirkmueller** [comment] 2020-09-02 10:32
Thanks for the detailed analysis and patch. this is now fixed in NRZ-2020-130-B6 or newer.

**Closed by dirkmueller** 2020-09-02 10:32 UTC
Labels: bug
