### ISSUE TITLE
Empty chart in AirTube

### ISSUE THREAD

**Issue by IvanKarchev** [opendata-stuttgart/sensors-software#712] opened 2020-04-29 18:37 UTC
Hello guys, I have strange problem with data in AirTube website. Sensor working correctly but there is no data in datatable.
![Screenshot_2020-04-29-21-23-11-056_com brave browser](https://user-images.githubusercontent.com/64553033/80632996-c08a3d00-8a60-11ea-8ebd-365c5cdeed91.jpg)
Can you guys help me to solve this problem. I try to reach there support but nobody answered.
You can check my sensor.
![Screenshot_2020-04-29-21-34-48-878_com brave browser](https://user-images.githubusercontent.com/64553033/80633364-4e662800-8a61-11ea-974e-1e847479b932.jpg)

And this is the coordinates
![Screenshot_2020-04-29-21-36-42-022_com brave browser](https://user-images.githubusercontent.com/64553033/80633533-98e7a480-8a61-11ea-81f5-6fef61e807e9.jpg)

**Comment by Petarkir2000** [comment] 2020-04-29 19:39
The issue you should address to airtube.info - info@airtube.info

**Comment by ricki-z** [comment] 2020-09-02 11:24
@IvanKarchev can we close this issue? The problem isn't related to a website we are maintaining. So we can't solve this.

**Comment by dirkmueller** [comment] 2020-09-02 20:03
Please report to the airtube.info site maintainers. Thanks for your understanding!

**Closed by dirkmueller** 2020-09-02 20:03 UTC

**Comment by IvanKarchev** [comment] 2020-09-03 09:14
Yes, close it.
I need to clear the sensor tube coz it give the high values.
Thank you, best regards,
ivan
