### ISSUE TITLE
Sensor is removed from sensor community map after maximize intervall

### ISSUE THREAD

**Issue by atze09** [opendata-stuttgart/sensors-software#698] opened 2020-03-23 19:40 UTC
Hello,
I have a question concerning the sensor community map.
I startet with my noise sensor yesterday with an measurement intervall of 1 minute, i saw that this was too much date, so i switched to half an hours.
Now my sensor is gone from the map.
Is there i maximum intervall in that the sensor appears in the map.
i am currently trying with 15 minutes.

Thank you in advance.
Best regards,
Dominik

**Comment by ricki-z** [comment] 2020-03-24 06:58
We show only sensor on the map that have sent data within the last 5 minutes.
To have comparable measurements the interval should be 145 seconds. This is the default for all devices with our firmware.

**Comment by Marwe** [comment] 2020-03-30 00:03
duplicate of #643 
answered, so closing

**Closed by Marwe** 2020-03-30 00:03 UTC
