### ISSUE TITLE
Deepsleep option

### ISSUE THREAD

**Issue by remyderuysscher** [opendata-stuttgart/sensors-software#174] opened 2017-12-09 13:56 UTC
I have an ESP8266 and would like to use the deep sleep option, since mine is battery powered.

This requires a hardware modification GPIO16 needs to be tied to RST to wake from deepSleep.

A software configurable timer would be nice 5, 10, 15 min.

The function is called ESP.deepSleep(microseconds, mode) will put the chip into deep sleep. mode is one of WAKE_RF_DEFAULT, WAKE_RFCAL, WAKE_NO_RFCAL, WAKE_RF_DISABLED.

**Comment by Adorfer** [comment] 2017-12-09 14:17
See https://github.com/opendata-stuttgart/sensors-software/issues/104

**Comment by DeeKey** [comment] 2019-12-30 16:09
@dirkmueller please close as duplicate

**Comment by dirkmueller** [comment] 2019-12-30 17:13
Duplicate of #104

**Closed by dirkmueller** 2019-12-30 17:13 UTC
