### ISSUE TITLE
Wrong data SDS011 ?

### ISSUE THREAD

**Issue by Rewop-jpc** [opendata-stuttgart/sensors-software#680] opened 2020-02-28 11:09 UTC
The values in the graphs are very different from the values I retrieve from my sensor ?
Feinstaubsensor-11453096
https://www.sysanalyser.com/stofmap.html

**Comment by ricki-z** [comment] 2020-03-02 23:08
There are some implementations for home assistant systems that use the same data to generate graphs. And until now we haven't heard about any problems.
So this may a problem on your side. But we can't tell much about this as this is a "black box" for us.

**Comment by Rewop-jpc** [comment] 2020-03-03 15:39
I disconnected it for a while. After starting it up again, the graphs now looks much alike. Before your graph looked very unnaturally. Strait horizontal lines with a few spikes. Now it looks normal!

**Comment by ricki-z** [comment] 2020-03-04 09:32
@Rewop-jpc so the issue is solved? Then please close it.

**Closed** 2020-03-04 13:04 UTC
