### ISSUE TITLE
Temperatur Korrektur

### ISSUE THREAD

**Issue by fotodesigner** [opendata-stuttgart/sensors-software#722] opened 2020-05-18 16:39 UTC
As friedpa wrote on march for DHT22....
Would it be possible to implement a correcture value to the DHT22 as the measurement,
but now for the BME280
Temperature was displayed differently by different modules, currently a constant difference of approx. + 2 degrees Celsius.
Kind Regards

**Comment by dirkmueller** [comment] 2020-09-02 10:56
This is basically a duplicate of #607 . The feature is implemented in NRZ-2020-130-B2 or later.

**Closed by dirkmueller** 2020-09-02 10:56 UTC
Labels: enhancement
